# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23c45c5f14c2a81defef441555b01d7bd79ce87f0a4d80443657c8acbc57c11faf71284473727c7cccb6b0c68ff10b86dc0293e88d2cef0ebe81f6ae9da324ce04c0f
  # secret_key_base: 23c45c5f14c2a81441555b01d7bd79ce87f0a4d80443657c8acbc57c11faf71284473727c7cccb6b0c68ff10b86dc0293e88d2cef0ebe81f6ae9da324ce04c0f


test:
  secret_key_base: 6f8de63e45a9f401acf99dfdfdfd46e0d19882ff572d2cd317f94e8ee575813ddcabf07bc358cf8eb6d6c077b04a543962bbc154d4a2993ff0fe8cd5448cbc120eb6a79
  # secret_key_base: 6f8de63e45a9f401acf9946e0d19882ff572d2cd317f94e8ee575813ddcabf07bc358cf8eb6d6c077b04a543962bbc154d4a2993ff0fe8cd5448cbc120eb6a79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
